use crate::error::{KicadError, Result};
use std::collections::HashMap;
use std::collections::hash_map::Entry;

pub struct ModelExporter;

impl ModelExporter {
    pub fn new() -> Self {
        Self
    }

    /// Convert OBJ format to VRML (.wrl) format
    pub fn obj_to_wrl(&self, obj_data: &[u8]) -> Result<String> {
        let obj_str = String::from_utf8_lossy(obj_data);

        // Parse materials and vertices
        let materials = self.parse_obj_materials(&obj_str);
        let vertices = self.parse_obj_vertices(&obj_str)?;
        let sections = self.parse_obj_faces(&obj_str, vertices.len())?;

        // Generate VRML output
        let mut output = String::new();
        output.push_str("#VRML V2.0 utf8\n");
        output.push_str("# 3D model generated by HappyJLC (https://github.com/Alddp/happyjlc)\n");

        for (material_name, faces) in sections {
            let material = materials.get(&material_name).cloned().unwrap_or(Material {
                diffuse: (0.8, 0.8, 0.8),
                specular: (0.5, 0.5, 0.5),
            });

            // Process faces for this material
            let mut link_dict: HashMap<usize, usize> = HashMap::new();
            let mut coord_index = Vec::new();
            let mut points = Vec::new();

            for face in faces {
                let mut face_index = Vec::with_capacity(face.len() + 1);

                for index in face {
                    let local_index = match link_dict.entry(index) {
                        Entry::Vacant(entry) => {
                            let local_index = points.len();
                            points.push(vertices[index].clone());
                            entry.insert(local_index);
                            local_index
                        }
                        Entry::Occupied(entry) => *entry.get(),
                    };
                    face_index.push(local_index as i32);
                }

                face_index.push(-1);
                coord_index.push(face_index);
            }

            // Generate Shape for this material
            output.push_str("\nShape {\n");
            output.push_str("  appearance Appearance {\n");
            output.push_str("    material Material {\n");
            output.push_str(&format!(
                "      diffuseColor {} {} {}\n",
                material.diffuse.0, material.diffuse.1, material.diffuse.2
            ));
            output.push_str(&format!(
                "      specularColor {} {} {}\n",
                material.specular.0, material.specular.1, material.specular.2
            ));
            output.push_str("      ambientIntensity 0.2\n");
            output.push_str("      transparency 0\n");
            output.push_str("      shininess 0.5\n");
            output.push_str("    }\n");
            output.push_str("  }\n");
            output.push_str("  geometry IndexedFaceSet {\n");
            output.push_str("    ccw TRUE\n");
            output.push_str("    solid FALSE\n");
            output.push_str("    coord DEF co Coordinate {\n");
            output.push_str("      point [\n");

            // Write vertices
            for (i, vertex) in points.iter().enumerate() {
                if i < points.len() - 1 {
                    output.push_str(&format!("        {}, ", vertex));
                } else {
                    output.push_str(&format!("        {}\n", vertex));
                }
            }

            output.push_str("      ]\n");
            output.push_str("    }\n");
            output.push_str("    coordIndex [\n");

            // Write face indices
            for (i, face) in coord_index.iter().enumerate() {
                output.push_str("      ");
                for (j, idx) in face.iter().enumerate() {
                    if j < face.len() - 1 {
                        output.push_str(&format!("{}, ", idx));
                    } else {
                        output.push_str(&format!("{}", idx));
                    }
                }
                if i < coord_index.len() - 1 {
                    output.push_str(",\n");
                } else {
                    output.push('\n');
                }
            }

            output.push_str("    ]\n");
            output.push_str("  }\n");
            output.push_str("}\n");
        }

        if output.lines().count() <= 2 {
            return Err(KicadError::ModelExport("OBJ contains no faces".to_string()).into());
        }

        Ok(output)
    }

    /// Export STEP file (just write binary data as-is)
    pub fn export_step(&self, step_data: &[u8]) -> Result<Vec<u8>> {
        Ok(step_data.to_vec())
    }

    fn parse_obj_vertices(&self, obj: &str) -> Result<Vec<String>> {
        let mut vertices = Vec::new();

        for line in obj.lines() {
            let line = line.trim();
            if line.starts_with("v ") {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 4 {
                    let x = parts[1].parse::<f64>().map_err(|_| {
                        KicadError::ModelExport("Invalid vertex X coordinate".to_string())
                    })?;
                    let y = parts[2].parse::<f64>().map_err(|_| {
                        KicadError::ModelExport("Invalid vertex Y coordinate".to_string())
                    })?;
                    let z = parts[3].parse::<f64>().map_err(|_| {
                        KicadError::ModelExport("Invalid vertex Z coordinate".to_string())
                    })?;

                    // Convert from mm to inches by dividing by 2.54, round to 4 decimals
                    let vx = format!("{:.4}", x / 2.54);
                    let vy = format!("{:.4}", y / 2.54);
                    let vz = format!("{:.4}", z / 2.54);

                    vertices.push(format!("{} {} {}", vx, vy, vz));
                }
            }
        }

        Ok(vertices)
    }

    fn parse_obj_faces(
        &self,
        obj: &str,
        vertex_count: usize,
    ) -> Result<Vec<(String, Vec<Vec<usize>>)>> {
        let mut sections: Vec<(String, Vec<Vec<usize>>)> = Vec::new();
        let mut material_name = String::new();

        for line in obj.lines() {
            let line = line.trim();
            if let Some(name) = line.strip_prefix("usemtl ") {
                material_name = name.split_whitespace().next().unwrap_or("").to_string();
                continue;
            }

            if !line.starts_with("f ") {
                continue;
            }

            let fields: Vec<&str> = line.split_whitespace().skip(1).collect();
            if fields.len() < 3 {
                return Err(KicadError::ModelExport(format!(
                    "OBJ face has fewer than three vertices: {}",
                    line
                ))
                .into());
            }

            let indices = fields
                .into_iter()
                .map(|field| self.parse_obj_vertex_index(field, vertex_count))
                .collect::<Result<Vec<_>>>()?;

            if sections
                .last()
                .is_none_or(|(section_material, _)| *section_material != material_name)
            {
                sections.push((material_name.clone(), Vec::new()));
            }
            sections
                .last_mut()
                .expect("OBJ section should exist")
                .1
                .push(indices);
        }

        if sections.is_empty() {
            return Err(KicadError::ModelExport("OBJ contains no faces".to_string()).into());
        }

        Ok(sections)
    }

    fn parse_obj_vertex_index(&self, field: &str, vertex_count: usize) -> Result<usize> {
        let index = field
            .split('/')
            .next()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| {
                KicadError::ModelExport(format!("Invalid OBJ vertex reference: {}", field))
            })?
            .parse::<isize>()
            .map_err(|_| {
                KicadError::ModelExport(format!("Invalid OBJ vertex reference: {}", field))
            })?;

        let resolved = match index.cmp(&0) {
            std::cmp::Ordering::Greater => index - 1,
            std::cmp::Ordering::Less => vertex_count as isize + index,
            std::cmp::Ordering::Equal => {
                return Err(KicadError::ModelExport(
                    "OBJ vertex indices cannot be zero".to_string(),
                )
                .into());
            }
        };

        if resolved < 0 || resolved as usize >= vertex_count {
            return Err(KicadError::ModelExport(format!(
                "OBJ vertex index {} is out of range for {} vertices",
                index, vertex_count
            ))
            .into());
        }

        Ok(resolved as usize)
    }

    fn parse_obj_materials(&self, obj: &str) -> HashMap<String, Material> {
        let mut materials = HashMap::new();
        let mut current_material: Option<(String, Material)> = None;

        for line in obj.lines() {
            let line = line.trim();

            if line.starts_with("newmtl ") {
                // Save previous material if exists
                if let Some((name, mat)) = current_material.take() {
                    materials.insert(name, mat);
                }

                // Start new material
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 2 {
                    current_material = Some((
                        parts[1].to_string(),
                        Material {
                            diffuse: (0.8, 0.8, 0.8),
                            specular: (0.5, 0.5, 0.5),
                        },
                    ));
                }
            } else if let Some((_, ref mut mat)) = current_material {
                if line.starts_with("Kd ") {
                    // Diffuse color
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 4
                        && let (Ok(r), Ok(g), Ok(b)) = (
                            parts[1].parse::<f64>(),
                            parts[2].parse::<f64>(),
                            parts[3].parse::<f64>(),
                        )
                    {
                        mat.diffuse = (r, g, b);
                    }
                } else if line.starts_with("Ks ") {
                    // Specular color
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 4
                        && let (Ok(r), Ok(g), Ok(b)) = (
                            parts[1].parse::<f64>(),
                            parts[2].parse::<f64>(),
                            parts[3].parse::<f64>(),
                        )
                    {
                        mat.specular = (r, g, b);
                    }
                } else if line == "endmtl" {
                    // End of material definition
                    if let Some((name, mat)) = current_material.take() {
                        materials.insert(name, mat);
                    }
                }
            }
        }

        // Save last material if not ended with endmtl
        if let Some((name, mat)) = current_material {
            materials.insert(name, mat);
        }

        materials
    }
}

impl Default for ModelExporter {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone)]
struct Material {
    diffuse: (f64, f64, f64),
    specular: (f64, f64, f64),
}

#[cfg(test)]
mod tests {
    use super::ModelExporter;

    #[test]
    fn converts_standard_obj_face_references() {
        let obj = b"v 0 0 0\nv 2.54 0 0\nv 0 2.54 0\nf 1/1/1 2/2/1 3/3/1\n";
        let wrl = ModelExporter::new().obj_to_wrl(obj).unwrap();

        assert!(wrl.contains("Shape {"));
        assert!(wrl.contains("0.0000 0.0000 0.0000"));
        assert!(wrl.contains("0.0000 1.0000 0.0000"));
        assert!(wrl.contains("1.0000 0.0000 0.0000"));
        assert!(wrl.contains("0, 1, 2, -1"));
    }

    #[test]
    fn supports_faces_without_materials_and_negative_indices() {
        let obj = b"v 0 0 0\nv 2.54 0 0\nv 0 2.54 0\nf -3 -2 -1\n";
        let wrl = ModelExporter::new().obj_to_wrl(obj).unwrap();

        assert!(wrl.contains("Shape {"));
        assert!(wrl.contains("0, 1, 2, -1"));
    }

    #[test]
    fn rejects_invalid_obj_face_references() {
        let obj = b"v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 4\n";
        let error = ModelExporter::new().obj_to_wrl(obj).unwrap_err();

        assert!(error.to_string().contains("out of range"));
    }

    #[test]
    fn rejects_obj_without_faces_instead_of_emitting_empty_wrl() {
        let obj = b"v 0 0 0\nv 1 0 0\nv 0 1 0\n";
        let error = ModelExporter::new().obj_to_wrl(obj).unwrap_err();

        assert!(error.to_string().contains("no faces"));
    }
}
